-- 1. PROFILES (Roles & User Data)
create table if not exists profiles (
  id uuid references auth.users on delete cascade primary key,
  role text default 'customer' check (role in ('admin', 'delivery', 'customer')),
  full_name text,
  phone text,
  updated_at timestamp with time zone
);

-- Trigger to create profile on signup (Handle new Supabase users)
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', 'customer');
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid error on rerun
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. ORDERS
create table if not exists orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null, -- Null for guest checkout
  status text default 'pending' check (status in ('pending', 'paid', 'shipping', 'delivered', 'cancelled')),
  total_amount numeric not null,
  shipping_name text not null,
  shipping_phone text not null,
  shipping_address text not null,
  payment_method text default 'mpesa',
  payment_ref text, -- M-Pesa Receipt Number
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. ORDER ITEMS
create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references orders(id) on delete cascade not null,
  product_id bigint references merchandise(id) on delete set null,
  product_title text, -- Snapshot of title in case product is deleted
  quantity int not null check (quantity > 0),
  price_at_purchase numeric not null
);

-- 4. ENABLE RLS
alter table profiles enable row level security;
alter table orders enable row level security;
alter table order_items enable row level security;

-- 5. POLICIES

-- PROFILES
create policy "Public read profiles" on profiles for select using (true); -- Needed for admin to see names? Or just restricted? Let's allow public for now or restricted.
-- Actually, strict security: Users see their own. Admins see all.
-- Drop existing potential policies to clean up if rerunning
drop policy if exists "Users see own profile" on profiles;
drop policy if exists "Admins/Delivery see all profiles" on profiles;
drop policy if exists "Users update own profile" on profiles;

create policy "Users see own profile" on profiles for select using (auth.uid() = id);
create policy "Admins/Delivery see all profiles" on profiles for select using (
  exists (select 1 from profiles where id = auth.uid() and role in ('admin', 'delivery'))
);
create policy "Users update own profile" on profiles for update using (auth.uid() = id);
create policy "Admins update all profiles" on profiles for update using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
);

-- ORDERS
drop policy if exists "Users see own orders" on orders;
drop policy if exists "Admins/Delivery see all orders" on orders;
drop policy if exists "Public insert orders" on orders;
drop policy if exists "Admins/Delivery update orders" on orders;

create policy "Users see own orders" on orders for select using (auth.uid() = user_id);
create policy "Admins/Delivery see all orders" on orders for select using (
  exists (select 1 from profiles where id = auth.uid() and role in ('admin', 'delivery'))
);
create policy "Public insert orders" on orders for insert with check (true);
create policy "Admins/Delivery update orders" on orders for update using (
  exists (select 1 from profiles where id = auth.uid() and role in ('admin', 'delivery'))
);

-- ORDER ITEMS
drop policy if exists "Users see own order items" on order_items;
drop policy if exists "Admins/Delivery see all order items" on order_items;
drop policy if exists "Public insert order items" on order_items;

create policy "Users see own order items" on order_items for select using (
  exists (select 1 from orders where orders.id = order_items.order_id and orders.user_id = auth.uid())
);
create policy "Admins/Delivery see all order items" on order_items for select using (
    exists (select 1 from profiles where id = auth.uid() and role in ('admin', 'delivery'))
);
create policy "Public insert order items" on order_items for insert with check (true);

-- 6. INDEXES for Performance
create index if not exists idx_orders_user_id on orders(user_id);
create index if not exists idx_order_items_order_id on order_items(order_id);
