-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. IMAGES BUCKET (Storage)
insert into storage.buckets (id, name, public) 
values ('images', 'images', true)
on conflict (id) do nothing;

create policy "Public Access"
  on storage.objects for select
  using ( bucket_id = 'images' );

create policy "Authenticated Insert"
  on storage.objects for insert
  with check ( bucket_id = 'images' and auth.role() = 'authenticated' );

create policy "Authenticated Update"
  on storage.objects for update
  using ( bucket_id = 'images' and auth.role() = 'authenticated' );

create policy "Authenticated Delete"
  on storage.objects for delete
  using ( bucket_id = 'images' and auth.role() = 'authenticated' );

-- 2. TABLES

-- Create services table
create table if not exists services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  img_src text,
  icon text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create merchandise table
create table if not exists merchandise (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  price numeric not null,
  currency text default 'USD',
  sizes jsonb default '[]'::jsonb,
  images jsonb default '[]'::jsonb,
  sku text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create team_members table
create table if not exists team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  bio text,
  img_src text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create testimonials table
create table if not exists testimonials (
  id bigint generated by default as identity primary key,
  name text not null,
  quote text not null,
  img_src text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create timeline_events table (About page)
create table if not exists timeline_events (
  id bigint generated by default as identity primary key,
  period text not null,
  title text not null,
  description text,
  img_src text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create blog_posts table
create table if not exists blog_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique not null,
  category text,
  author text,
  content text,
  img_src text,
  published_at timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create contact_messages table
create table if not exists contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  message text,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create site_settings table (for global values like logos, footer text)
create table if not exists site_settings (
  key text primary key,
  value text,
  description text
);

-- 3. ENABLE RLS (Row Level Security)
alter table services enable row level security;
alter table merchandise enable row level security;
alter table team_members enable row level security;
alter table testimonials enable row level security;
alter table timeline_events enable row level security;
alter table blog_posts enable row level security;
alter table contact_messages enable row level security;
alter table site_settings enable row level security;

-- 4. POLICIES (Public Read, Admin Write)

-- Services: Public read, Anon read (for now), Auth write
create policy "Public Read Services" on services for select using (true);
create policy "Auth Write Services" on services for all using (auth.role() = 'authenticated');

-- Merchandise
create policy "Public Read Merchandise" on merchandise for select using (true);
create policy "Auth Write Merchandise" on merchandise for all using (auth.role() = 'authenticated');

-- Team Members
create policy "Public Read Team" on team_members for select using (true);
create policy "Auth Write Team" on team_members for all using (auth.role() = 'authenticated');

-- Testimonials
create policy "Public Read Testimonials" on testimonials for select using (true);
create policy "Auth Write Testimonials" on testimonials for all using (auth.role() = 'authenticated');

-- Timeline
create policy "Public Read Timeline" on timeline_events for select using (true);
create policy "Auth Write Timeline" on timeline_events for all using (auth.role() = 'authenticated');

-- Blog Posts
create policy "Public Read Blogs" on blog_posts for select using (true);
create policy "Auth Write Blogs" on blog_posts for all using (auth.role() = 'authenticated');

-- Contact Messages (Public can insert, only Auth can read)
create policy "Public Insert Messages" on contact_messages for insert with check (true);
create policy "Auth Read Messages" on contact_messages for select using (auth.role() = 'authenticated');
create policy "Auth Update Messages" on contact_messages for update using (auth.role() = 'authenticated');
create policy "Auth Delete Messages" on contact_messages for delete using (auth.role() = 'authenticated');

-- Site Settings
create policy "Public Read Settings" on site_settings for select using (true);
create policy "Auth Write Settings" on site_settings for all using (auth.role() = 'authenticated');


-- 5. SEED DATA (Optional initial data)
insert into site_settings (key, value, description) values 
('site_title', 'Project MindStrong', 'Main website title'),
('contact_email', 'info@projectmindstrong.com', 'Contact email address')
on conflict (key) do nothing;

